export const data = [
    {   id:1,
        name:"Mustang",
        img_url:"https://shorturl.at/iBW78",
        price:"$1000",
        amount:0,
    },
    {   id:2,
        name:"BMW",
        img_url:"https://shorturl.at/oCKLM",
        price:"$1000",
        amount:0,
    },
    {   id:3,
        name:"Mercedes",
        img_url:"https://shorturl.at/efqG9",
        price:"$1000",
        amount:0,
    },
    {   id:4,
        name:"Audi",
        img_url:"https://shorturl.at/lxBNY",
        price:"$1000",
        amount:0,
    },
];